<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHguW1zm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHguW1zm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHguW1zm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHguW1zm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHguW1zm\App_KernelDevDebugContainer([
    'container.build_hash' => 'HguW1zm',
    'container.build_id' => '527588f0',
    'container.build_time' => 1738507976,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHguW1zm');
